### ISSUE TITLE
Invite members to group

### ISSUE THREAD

**Issue by Pdbz199** [mortorqrobotics/MorTeam-Server-Website#1]
I should not be able to invite members to a group in which they already are.

**Comment by Farbod909** [comment]
I'll look into it. Do you know what happens when you attempt to do that? Does the other person get the invite?

**Comment by Pdbz199** [comment]
I'm not sure. I don't think anything happens. Also, I shouldn't be able to invite myself. It doesn't appear to do anything when you invite yourself at least.

**Comment by Farbod909** [comment]
Will no longer send invites to members/invited people.
