### ISSUE TITLE
Allow team departure

### ISSUE THREAD

**Issue by afuous** [mortorqrobotics/morteam-server-website#31]
This involves a few new features:

- [x] 1. Add a "Leave" button on the team page.
- [x] 2. Display the team code on the team page.
- [x] 3. Allow a user to remove himself from his team

Any high-impact actions, like leaving a team, should present the user with sufficient warning to prevent bad accidents.

**Comment by E-A-A** [comment]
This is addressed by the allow-team-departure branch on client.

**Comment by AriellaS** [comment]
In server, this is being addressed by the team-leaving branch
