### ISSUE TITLE
Lone Admins can demote themselves to Leader, leaving no Admins in a team.

### ISSUE THREAD

**Issue by mryork** [mortorqrobotics/morteam-server-website#6]
In the "View Profile" section, team Admins can demote themselves to the Leader position, leaving no Admins on team.

**Comment by voidpigeon** [comment]
This was changed.

**Comment by mryork** [comment]
Would there be a way to automatically promote lone Leaders to Admin, if there are no Admins on the team? This fix would allow for teams who already had the bug occur to still have an Admin on their team.
